# Generated by Django 2.2.3 on 2019-08-20 10:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newtest', '0004_auto_20190820_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='followed_by',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'followed_by')},
        ),
    ]
